# ----- CAMEL -----
camel:
  component:
    aws2-s3:
      region: us-east-1
      auto-create-bucket: false
      use-default-credentials-provider: true
    aws2-sqs:
      region: us-east-1
      auto-create-queue: false
      delete-after-read: true
      use-default-credentials-provider: true