# ----- Properties -----
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${DISCOVERY_SERVER_ENDPOINT:http://localhost:8761}
  profiles:
    active: default, eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-microservice-route
          uri: lb://authentication-microservice
          predicates:
            - Path=/api/v1/auth/**
        - id: user-microservice-route
          uri: lb://user-microservice
          predicates:
            - Path=/api/v1/users/**
        - id: sound-file-microservice-route
          uri: lb://sound-file-microservice
          predicates:
            - Path=/api/v1/sound-file/**
        - id: enricher-microservice-route
          uri: lb://music-enricher-microservice
          predicates:
            - Path=/api/v1/enrich/**
        - id: track-microservice-route
          uri: lb://track-microservice
          predicates:
            - Path=/api/v1/**

# ----- Server -----
server:
  port: 8080

origin:
  endpoint: ${ORIGIN_ENDPOINT:localhost:4200}
