# ----- Properties -----
spring:
  config:
    import: optional:configserver:http://localhost:8761
  profiles:
    active: default, eureka, mysql, jwt, security
  application:
    name: authentication-microservice
  datasource:
    url: jdbc:mysql://localhost:3306/song-dashboard-api
  liquibase:
    default_schema: song-dashboard-api
    change-log: classpath:/db/changelog/users-roles-changelog/changelog.yaml

# ----- Server -----
server:
  port: 0